### ISSUE TITLE
💡   Suggestions for simple and intuitive Pull Request Template file

### ISSUE THREAD

**Issue by YaadR** [Twiggecode/Integer-Sequences#104]
##  Pull Requests Template

This is a simple 'first issue' to deal with, but require creativity and careful thinking.

#### General line of thought:
 - There is a Tracking List for the project under the file name [TrackingProgress.md](https://github.com/Twiggecode/Integer-Sequences/blob/main/TrackingProgress.md)
 - The idea is to encourage contributors to help to update the Tracking List or at least sum up their changes so it would be easier to follow, and for other contributors to complete the following update process.
 - The file [Pull Request Template.md](https://github.com/Twiggecode/Integer-Sequences/blob/main/Pull%20Request%20Template.md) is an example to edit and work on. Of course, your's can be something entirely different.

### for example:

- [x] I read the README file 
- [ ]  I've checked the code is compiling and working
- [ ]  I've updated the changes in  [TrackingProgress.md](https://github.com/Twiggecode/Integer-Sequences/blob/main/TrackingProgress.md)

*example for table*

| Sequence name | Added new \ Update existing | Language | Added new \ fixed issues |
| :---: | :---: | :---: | :---: |
| Prime Numbers | Update | C | new |

**Comment by Ash-KODES** [comment]
is this issue closed or i can still propose my thoughts??

**Comment by Varun270** [comment]
@Twiggecode  I think we should also make a separate folder for algorithms in C, C++, Python, and Java. Let's just not bound this repository to just number sequences.

**Comment by Twiggecode** [comment]
@Varun270 This is something to consider in the future, I think I will just continue with the number sequences format for the time being though.

**Comment by YaadR** [comment]
@Twiggecode 

Can you please help me out with labelling the issue?
It seems that I don't have the option myself
![2](https://user-images.githubusercontent.com/85457983/128482498-7429fbd4-fcd4-42df-a705-3b7ef69db40e.JPG)

**Comment by Twiggecode** [comment]
@YaadR I've added some labels just now.

**Comment by YaadR** [comment]
Thanks

**Comment by Onyinye91-ctrl** [comment]
Hello @YaadR  is this issue still available? if yes, Can i work on it?

**Comment by YaadR** [comment]
Hi  @Onyinye91-ctrl 
@Twiggecode is the project admin. 
As long as he leaves this issue open, it is relevant.
Go for it 👍🏽

**Comment by Onyinye91-ctrl** [comment]
Okay @YaadR

**Comment by Twiggecode** [comment]
Hey @Onyinye91-ctrl 

The pull request template still needs some work, so I am leaving the issue open for now and anyone is free to work on it.
