### ISSUE TITLE
🗺️  Help translate README  to more languages

### ISSUE THREAD

**Issue by YaadR** [Twiggecode/Integer-Sequences#129]
# README Translation

#### If your native tongue is other but English, or you just happen to have another fluent language, then this is for you! 🌏 

**Key Notes:**
-  Make sure you fully understand the original README at first and translate it as reliable as you can to the EN source version.
- Don't translate the original README.md file, i.e don't replace it with other translations.
- Create a new README file with the new language symbolic letters. *example:* **README_EN.md**.
- If the Translation is not complete while committing PR - mention it and raise an issue for completion if help is needed. 
- Make sure all the hyperlinks are existing and working.
- Once approved and merged, add a relevant link to the original ReadMe languages list.
![2](https://user-images.githubusercontent.com/85457983/129058214-5f041800-aaaf-45f6-9aa1-213c5033bcd3.JPG)

**Comment by Twiggecode** [comment]
Not something I am able to help with personally, but for others who are fluent in other languages, please help if you can.

Thank you.

**Comment by mark7588** [comment]
I am willing to work on Korean version of README today.

**Comment by RajPabnani03** [comment]
I am willing to work on Hindi version of README today.

**Comment by YaadR** [comment]
Go for it 👍🏽

**Comment by Edmartt** [comment]
I've made a pull request with the spanish translation, any advice welcome. :)

**Comment by RajPabnani03** [comment]
I've made a pull request with the Hindi translation .

**Comment by Twiggecode** [comment]
@RajPabnani03 I can't see your pull request, just letting you know in case you intended to submit one and forgot.

**Comment by RajPabnani03** [comment]
> @RajPabnani03 I can't see your pull request, just letting you know in case you intended to submit one and forgot.

I will Do it again Right away ...

**Comment by varunwho** [comment]
I'll make for french

**Comment by benedictusdps** [comment]
I'll make one for Indonesian

**Comment by Ghost1499** [comment]
I just translated readme.md in Russian and sent a pull request.

**Comment by Sedatyf** [comment]
To keep track of it, I made a translation in French. I also sorted every languages in alphabetical order in #197

**Comment by Sagun-png** [comment]
@Twiggecode Someone already sent the PR for Hindi but I couldn't see that attached. So I would like to contribute in Hindi.

**Comment by Twiggecode** [comment]
@Sagun-png He never submitted a pull request for the Hindi translation, so you are free to create the Hindi translation if you'd like.

**Comment by Sagun-png** [comment]
@Twiggecode Thanks for the opportunity. I'll submit.

**Comment by rajsanu** [comment]
@Twiggecode I am Sanu Raj. i have created a pull request for Hindi translation of the README. I am new to github, and this was my first ever pull request. Please guide me if I have made any mistakes. I am ready to learn. Thank you

**Comment by Daxin-H** [comment]
I fiinshed the Chinese version of Readme, and I make a pull request. Please have a look about it.

**Comment by soumyajyoti1999** [comment]
Willing to work upon the Bengali version of READ ME

**Comment by Rs-py** [comment]
Hey @Twiggecode, I created an Arabic translation for the README file and submitted a pull request. This was my first PR thanks for the opportunity and let me know if anything needs to be changed.
