### ISSUE TITLE
Help make this project more accessible to numerically challenged problem solvers 🤓

### ISSUE THREAD

**Issue by shr100** [Twiggecode/Integer-Sequences#232]
Add a README.md to each of the sub-directories explaining what each problem statement aims to accomplish. For example, Abundant Numbers are those positive integers whose sum of the divisors are greater than the integer itself. Throw in a few examples if you can.

**Comment by Twiggecode** [comment]
Hi shr100, all of this information is explained to a much higher standard than what I'm capable of on Wikipedia. There is a link to the Wikipedia page describing all of the integer sequences in my readme file.
